## Practical 7 - Python for Data Science

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import numpy as np

### **1> Write a Python program to create an int, character and float array using array module.**

In [3]:
from array import *

In [4]:
# int array
int_array = array('i', [1,2,3,4])
print(int_array)
print(type(int_array[0]))

array('i', [1, 2, 3, 4])
<class 'int'>


In [5]:
# char array
char_array = array('u', ['a','b','c','d'])
print(char_array)
print(type(char_array[0]))

array('u', 'abcd')
<class 'str'>


In [6]:
# float array
float_array = array('f',[1.2,3.4,6.7,9.8])
print(float_array)
print(type(float_array[0]))

array('f', [1.2000000476837158, 3.4000000953674316, 6.699999809265137, 9.800000190734863])
<class 'float'>


### **2> Create an array of 1 to 20 in reverse order using arange function.**

In [7]:
import numpy as np

In [8]:
a = np.arange(20,0,-1)
print(a)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


### **3> Create an integer array from a range between 100 to 200 such that <br>the difference between each element is 15.**

In [9]:
# using arange
a1 = np.arange(100,201,15)
print(a1)

[100 115 130 145 160 175 190]


### **4> Create an array of string using appropriate method.**

In [10]:
string_array = np.array(['abhi','jha','019'], dtype='str')
print(string_array)
print(type(string_array[0]))

['abhi' 'jha' '019']
<class 'numpy.str_'>


### **5> Write a NumPy program to create an array of 10 zeros,10 ones.**

In [11]:
one_array = np.ones(10)
zero_array = np.zeros(10)
print(one_array)
print(zero_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### **6> create an array of 10 values from 1 to 5 evenly spaced.**

In [12]:
even_array = np.linspace(1,5,10)
print(even_array)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### **7> create an array of 10 values from 1 to 5 evenly spaced on logscale.**

In [13]:
log_array = np.logspace(1,5,10)
print(log_array)

[1.00000000e+01 2.78255940e+01 7.74263683e+01 2.15443469e+02
 5.99484250e+02 1.66810054e+03 4.64158883e+03 1.29154967e+04
 3.59381366e+04 1.00000000e+05]


### **8> Get a 4 by 4 array of samples from the standard normal distribution using normal.**

In [14]:
normal_array = np.random.standard_normal(size=(4,4))
print(normal_array)

[[ 0.92923346 -0.47082026 -1.0012884   0.81183158]
 [ 0.12259821 -0.16176495  0.24360007 -0.01924016]
 [-0.88225647  1.30979388  1.60211669 -0.33638728]
 [ 0.02008378 -0.04126325  1.41866485  0.31389457]]


## **Practical 7.2 - Advanced Numpy**

### **1> Create a 4X2 integer array and Prints its attributes. Note: The element must be a type ofunsigned int16. And print the following Attributes: –**

In [15]:
# uint16 is data type notation of unsigned int16
uint_array = np.array([[1,2],[3,4],[5,6],[7,8]], dtype='uint16')

# attributes of array
print(f"a. Shape of array = {uint_array.shape}")
print(f"a. Array dimensions = {uint_array.ndim}")
print(f"c. Length of each element of the array in bytes = {uint_array.itemsize} bytes")
print(f"   Total array size in bytes = {uint_array.nbytes} bytes")

a. Shape of array = (4, 2)
a. Array dimensions = 2
c. Length of each element of the array in bytes = 2 bytes
   Total array size in bytes = 16 bytes


### **2> Create a 5X2 integer array from a range between 100 to 200<br> such that the difference between each element is 10.**

In [16]:
arr = np.arange(100, 200, 10)
arr = arr.reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


### **3> Following is the given numpy array, return array of odd rows and even columns**

In [17]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42,45, 48], [51 ,54, 57, 60]])
print("Original array = ")
print(sampleArray)

myArray = sampleArray[::2, 1::2]
print("\nArray of odd rows and even columns = ")
print(myArray)

Original array = 
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Array of odd rows and even columns = 
[[ 6 12]
 [30 36]
 [54 60]]


### **4> Following is the 2-D array. Print max from axis 0 and min from axis 1**

In [18]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(f"Original array =\n {sampleArray}")

# max from axis 0
arr1 = np.amax(sampleArray, axis = 0)
print(f"\nMax from axis 0 = {arr1}")

# min from axis 1
arr2 = np.amin(sampleArray, axis = 1)
print(f"Min from axis 1 = {arr2}")

Original array =
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

Max from axis 0 = [82 94 73]
Min from axis 1 = [34 12 53]


### **5> Finding means**

In [19]:
# a - creating array for given data
data = np.array([[0.12,0.08,0.06,0.02], [0.01,0.07,0.11,0.09], [0.03,0.04,0.04,0.02], [0.05,0.09,0.11,0.14]])

In [20]:
# b - find the mean expression value per gene
gene_mean = np.mean(data, axis=1)
gene1 = gene_mean[0]
gene2 = gene_mean[1]
gene3 = gene_mean[2]
gene4 = gene_mean[3]

In [21]:
# c - find the mean expression value per time point
time_mean = np.mean(data, axis=0)
time1 = time_mean[0]
time2 = time_mean[1]
time3 = time_mean[2]
time4 = time_mean[3]

In [22]:
# d - calculating mean expression values
g1 = gene1 * (time1 + time2 + time3 + time4)
g2 = gene2 * (time1 + time2 + time3 + time4)
g3 = gene3 * (time1 + time2 + time3 + time4)
g4 = gene4 * (time1 + time2 + time3 + time4)
means = {"A2M":g1, "FOS":g2, "BRCA2":g3, "CPOX":g4}

print(f"A2M = {g1}")
print(f"FOS = {g2}")
print(f"BRCA2 = {g3}")
print(f"CPOX = {g4}")
maxx = max(means, key=means.get)
print(f"{maxx} has maximum mean expression = {means[maxx]}")

A2M = 0.018900000000000004
FOS = 0.018900000000000004
BRCA2 = 0.008775000000000002
CPOX = 0.026325
CPOX has maximum mean expression = 0.026325


In [23]:
# e - sort the gene names by the max expression value
new = dict(sorted(means.items(), key = lambda key:key[1]))
print("Gene names in increasing order of mean expression is:")
for key,value in new.items():
    print(key)

Gene names in increasing order of mean expression is:
BRCA2
A2M
FOS
CPOX


### **6> Write a python program to demonstrate the concept of vectorization and show its <br> effectiveness over elementwise computations.**

In [24]:
import time
import array

In [25]:
# Array A = 1 x n
A = array.array('q')
for i in range(100000):
    A.append(i)

# Array B = n x 1
B = array.array('q')
for i in range(100000, 200000):
    B.append(i)

In [26]:
# A X B using for loop
start1 = time.process_time()
dot1 = 0
for i in range(len(A)):
    dot1 += A[i] * B[i]
    
end1 = time.process_time()
print(f"Dot product = {dot1}")
print(f"Computation time using for loop = {str(1000*(end1-start1))} ms")

Dot product = 833323333350000
Computation time using for loop = 119.26961600000041 ms


In [27]:
# A X B using dot method of numpy
start2 = time.process_time()
dot2 = np.dot(A,B)
end2 = time.process_time()
print(f"Dot product = {dot2}")
print(f"Computation time using dot method = {str(1000*(end2-start2))} ms")

Dot product = 833323333350000
Computation time using dot method = 2.3672259999996115 ms
